### ISSUE TITLE
无法授权 

### ISSUE THREAD

**Issue by gaoyike** [yfli/twitter-to-weibo-appengine#5]
http://liftwebcn.appspot.com/
授权错误

错误信息 
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/_webapp25.py", line 714, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/s~urfatu-tw-weibo/1.365162181894530815/app.py", line 55, in get
    self.response.out.write(template.render('error.html', {'message': 'Invalid token!'}))
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/template.py", line 91, in render
    t = _load_user_django(template_path, debug)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/template.py", line 113, in _load_user_django
    template = django.template.loader.get_template(file_name)
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/loader.py", line 79, in get_template
    source, origin = find_template_source(template_name)
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/loader.py", line 72, in find_template_source
    raise TemplateDoesNotExist, name
TemplateDoesNotExist: error.html

**Comment by gaoyike** [comment]
已经解决
